"""Обратная совместимость: конфигурация перенесена в корневой config.py."""

from config import (
    GIGACHAT_API_BASE_URL,
    GIGACHAT_BASE_CONFIG,
    GIGACHAT_CREATIVE_CONFIG,
    GIGACHAT_DEFAULT_MAX_TOKENS,
    GIGACHAT_DEFAULT_MODEL,
    GIGACHAT_DEFAULT_SCOPE,
    GIGACHAT_DEFAULT_TEMPERATURE,
    GIGACHAT_DEFAULT_TIMEOUT,
    GIGACHAT_OAUTH_URL,
    GIGACHAT_PLUS_CONFIG,
    GIGACHAT_PRECISE_CONFIG,
    GIGACHAT_PRO_CONFIG,
    GIGACHAT_VERIFY_SSL,
    GigaChatConfig,
)

__all__ = [
    "GigaChatConfig",
    "GIGACHAT_OAUTH_URL",
    "GIGACHAT_API_BASE_URL",
    "GIGACHAT_DEFAULT_SCOPE",
    "GIGACHAT_DEFAULT_MODEL",
    "GIGACHAT_DEFAULT_TEMPERATURE",
    "GIGACHAT_DEFAULT_MAX_TOKENS",
    "GIGACHAT_DEFAULT_TIMEOUT",
    "GIGACHAT_VERIFY_SSL",
    "GIGACHAT_BASE_CONFIG",
    "GIGACHAT_PRO_CONFIG",
    "GIGACHAT_PLUS_CONFIG",
    "GIGACHAT_CREATIVE_CONFIG",
    "GIGACHAT_PRECISE_CONFIG",
]
